import json
from pathlib import Path
import plotting


BASE_DIR = Path(__file__).resolve().parent.parent

def load_root():
    input_file = BASE_DIR / "data" / "docs" / "kinematics.txt"
    kinematics_data = plotting.get_kinematics(input_file)
    matched_data = plotting.get_root(kinematics_data)
    event_data = {
       "identity": {
           "muplus": {
               "hasMuon": None,
               "isMuon": None,
               "ID": None,
           },
           "muminus": {
               "hasMuon": None,
               "isMuon": None,
               "ID": None,
           },
           "Kplus": {
               "hasMuon": None,
               "isMuon": None,
               "ID": None,
           },
       },
        "detector_presence": {
            "muplus": {
                "hasCalo": None,
                "hasRich": None,
            },
            "muminus": {
                "hasCalo": None,
                "hasRich": None,
            },
            "Kplus": {
                "hasCalo": None,
                "hasRich": None,
            },
        },
        "detector_usage": {
            "muplus": {
                "UsedRichAerogel": None,
                "UsedRich1Gas": None,
                "UsedRich2Gas": None,
            },
            "muminus": {
                "UsedRichAerogel": None,
                "UsedRich1Gas": None,
                "UsedRich2Gas": None,
            },
            "Kplus": {
                "UsedRichAerogel": None,
                "UsedRich1Gas": None,
                "UsedRich2Gas": None,
            },

        },
        "rich_thresholds": {
            "muplus": {
                "RichAboveElThres": None,
                "RichAboveMuThres": None,
                "RichAbovePiThres":None,
                "RichAboveKaThres": None,
                "RichAbovePrThres": None,
            },
            "muminus": {
                "RichAboveElThres": None,
                "RichAboveMuThres": None,
                "RichAbovePiThres": None,
                "RichAboveKaThres": None,
                "RichAbovePrThres": None,
            },
            "Kplus": {
                "RichAboveElThres": None,
                "RichAboveMuThres": None,
                "RichAbovePiThres": None,
                "RichAboveKaThres": None,
                "RichAbovePrThres": None,
            },
        },
        "pid": {
            "muplus": {
                "PIDe": None,
                "PIDmu": None,
                "PIDK": None,
                "PIDp": None,
                "PIDd": None,
                "ProbNNe": None,
                "ProbNNK": None,
                "ProbNNp": None,
                "ProbNNpi": None,
                "ProbNNmu": None,
                "ProbNNd": None,
                "ProbNNghost": None,
                "MC12TuneV2_ProbNNe": None,
                "MC12TuneV2_ProbNNmu": None,
                "MC12TuneV2_ProbNNpi": None,
                "MC12TuneV2_ProbNNk": None,
                "MC12TuneV2_ProbNNp": None,
                "MC12TuneV2_ProbNNghost": None,
                "MC12TuneV3_ProbNNe": None,
                "MC12TuneV3_ProbNNmu": None,
                "MC12TuneV3_ProbNNpi": None,
                "MC12TuneV3_ProbNNk": None,
                "MC12TuneV3_ProbNNp":None,
                "MC12TuneV3_ProbNNghost": None,
                "MC12TuneV4_ProbNNe": None,
                "MC12TuneV4_ProbNNmu": None,
                "MC12TuneV4_ProbNNpi": None,
                "MC12TuneV4_ProbNNk": None,
                "MC12TuneV4_ProbNNp": None,
                "MC12TuneV4_ProbNNghost": None,
                "MC12TuneV1_ProbNNe": None,
                "MC12TuneV1_ProbNNmu": None,
                "MC12TuneV1_ProbNNpi": None,
                "MC12TuneV1_ProbNNk": None,
                "MC12TuneV1_ProbNNp": None,
                "MC12TuneV1_ProbNNghost": None,

            },
            "muminus": {
                "PIDe": None,
                "PIDmu": None,
                "PIDK": None,
                "PIDp": None,
                "PIDd": None,
                "ProbNNe": None,
                "ProbNNK": None,
                "ProbNNp": None,
                "ProbNNpi": None,
                "ProbNNmu": None,
                "ProbNNd": None,
                "ProbNNghost": None,
                "MC12TuneV2_ProbNNe": None,
                "MC12TuneV2_ProbNNmu": None,
                "MC12TuneV2_ProbNNpi": None,
                "MC12TuneV2_ProbNNk": None,
                "MC12TuneV2_ProbNNp": None,
                "MC12TuneV2_ProbNNghost": None,
                "MC12TuneV3_ProbNNe": None,
                "MC12TuneV3_ProbNNmu": None,
                "MC12TuneV3_ProbNNpi": None,
                "MC12TuneV3_ProbNNk": None,
                "MC12TuneV3_ProbNNp": None,
                "MC12TuneV3_ProbNNghost": None,
                "MC12TuneV4_ProbNNe": None,
                "MC12TuneV4_ProbNNmu": None,
                "MC12TuneV4_ProbNNpi": None,
                "MC12TuneV4_ProbNNk": None,
                "MC12TuneV4_ProbNNp": None,
                "MC12TuneV4_ProbNNghost": None,
                "MC12TuneV1_ProbNNe": None,
                "MC12TuneV1_ProbNNmu": None,
                "MC12TuneV1_ProbNNpi": None,
                "MC12TuneV1_ProbNNk": None,
                "MC12TuneV1_ProbNNp": None,
                "MC12TuneV1_ProbNNghost": None,
            },
            "Kplus": {
                "PIDe": None,
                "PIDmu": None,
                "PIDK": None,
                "PIDp": None,
                "PIDd": None,
                "ProbNNe": None,
                "ProbNNK": None,
                "ProbNNp": None,
                "ProbNNpi": None,
                "ProbNNmu": None,
                "ProbNNd": None,
                "ProbNNghost": None,
                "MC12TuneV2_ProbNNe": None,
                "MC12TuneV2_ProbNNmu": None,
                "MC12TuneV2_ProbNNpi": None,
                "MC12TuneV2_ProbNNk": None,
                "MC12TuneV2_ProbNNp": None,
                "MC12TuneV2_ProbNNghost": None,
                "MC12TuneV3_ProbNNe": None,
                "MC12TuneV3_ProbNNmu": None,
                "MC12TuneV3_ProbNNpi": None,
                "MC12TuneV3_ProbNNk": None,
                "MC12TuneV3_ProbNNp": None,
                "MC12TuneV3_ProbNNghost": None,
                "MC12TuneV4_ProbNNe": None,
                "MC12TuneV4_ProbNNmu": None,
                "MC12TuneV4_ProbNNpi": None,
                "MC12TuneV4_ProbNNk": None,
                "MC12TuneV4_ProbNNp": None,
                "MC12TuneV4_ProbNNghost": None,
                "MC12TuneV1_ProbNNe": None,
                "MC12TuneV1_ProbNNmu": None,
                "MC12TuneV1_ProbNNpi": None,
                "MC12TuneV1_ProbNNk": None,
                "MC12TuneV1_ProbNNp": None,
                "MC12TuneV1_ProbNNghost": None,
            },
        },
        "kinematics": {
            "Bplus": {
                "P": None,
                "PT": None,
                "PE": None,
                "PX": None,
                "PY": None,
                "PZ": None,
                "M": None,
            },
            "J_psi_1S": {
                "P": None,
                "PT": None,
                "PE": None,
                "PX": None,
                "PY": None,
                "PZ": None,
                "M": None,
            },
            "muplus": {
                "P": None,
                "PT": None,
                "PE": None,
                "PX": None,
                "PY": None,
                "PZ": None,
                "M": None,
            },
            "muminus": {
                "P": None,
                "PT": None,
                "PE": None,
                "PX": None,
                "PY": None,
                "PZ": None,
                "M": None,}
            },
            "Kplus": {
                "P": None,
                "PT": None,
                "PE": None,
                "PX": None,
                "PY": None,
                "PZ": None,
                "M": None,
            },
        "track_vertex": {
            "Bplus":{
                "OWNPV_X": None,
                "OWNPV_Y": None,
                "OWNPV_Z": None,
                "OWNPV_XERR": None,
                "OWNPV_YERR": None,
                "OWNPV_ZERR": None,
                "OWNPV_CHI2": None,
                "OWNPV_NDOF": None,
                "OWNPV_COV_": None,
                "IP_OWNPV": None,
                "IPCHI2_OWNPV": None,
                "FD_OWNPV": None,
                "FD_CHI2_OWNPV": None,
                "DIRA_OWNPV": None,

            },
            "J_psi_1S": {
                "OWNPV_X": None,
                "OWNPV_Y": None,
                "OWNPV_Z": None,
                "OWNPV_XERR": None,
                "OWNPV_YERR": None,
                "OWNPV_ZERR": None,
                "OWNPV_CHI2": None,
                "OWNPV_NDOF": None,
                "OWNPV_COV_": None,
                "IP_OWNPV": None,
                "IPCHI2_OWNPV": None,
                "FD_OWNPV": None,
                "FD_CHI2_OWNPV": None,
                "DIRA_OWNPV": None,
                "ORVIX_X": None,
                "ORVIX_Y": None,
                "ORVIX_XERR": None,
                "ORVIX_YERR": None,
                "ORVIX_ZERR": None,
                "ORVIX_CHI2": None,
                "ORVIX_NDOF": None,
                "ORVIX_COV_": None,
                "FD_ORVIX": None,
                "FD_CHI2_ORVIX": None,
                "DIRA_ORVIX": None,
            },
            "muplus": {
                "OWNPV_X": None,
                "OWNPV_Y": None,
                "OWNPV_Z": None,
                "OWNPV_XERR": None,
                "OWNPV_YERR": None,
                "OWNPV_ZERR": None,
                "OWNPV_CHI2": None,
                "OWNPV_NDOF": None,
                "OWNPV_COV_": None,
                "IP_OWNPV": None,
                "IPCHI2_OWNPV": None,
                "ORVIX_X": None,
                "ORVIX_Y": None,
                "ORVIX_XERR": None,
                "ORVIX_YERR": None,
                "ORVIX_ZERR": None,
                "ORVIX_CHI2": None,
                "ORVIX_NDOF": None,
                "ORVIX_COV_": None,
            },
            "muminus": {
                "OWNPV_X": None,
                "OWNPV_Y": None,
                "OWNPV_Z": None,
                "OWNPV_XERR": None,
                "OWNPV_YERR": None,
                "OWNPV_ZERR": None,
                "OWNPV_CHI2": None,
                "OWNPV_NDOF": None,
                "OWNPV_COV_": None,
                "IP_OWNPV": None,
                "IPCHI2_OWNPV": None,
                "ORVIX_X": None,
                "ORVIX_Y": None,
                "ORVIX_XERR": None,
                "ORVIX_YERR": None,
                "ORVIX_ZERR": None,
                "ORVIX_CHI2": None,
                "ORVIX_NDOF": None,
                "ORVIX_COV_": None,
            },
            "Kplus": {
                "OWNPV_X": None,
                "OWNPV_Y": None,
                "OWNPV_Z": None,
                "OWNPV_XERR": None,
                "OWNPV_YERR": None,
                "OWNPV_ZERR": None,
                "OWNPV_CHI2": None,
                "OWNPV_NDOF": None,
                "OWNPV_COV_": None,
                "IP_OWNPV": None,
                "IPCHI2_OWNPV": None,
                "ORVIX_X": None,
                "ORVIX_Y": None,
                "ORVIX_XERR": None,
                "ORVIX_YERR": None,
                "ORVIX_ZERR": None,
                "ORVIX_CHI2": None,
                "ORVIX_NDOF": None,
                "ORVIX_COV_": None,

            },
            "vertex_decay": {
                "Bplus": {
                    "ENDVERTEX_X": None,
                    "ENDVERTEX_Y": None,
                    "ENDVERTEX_Z": None,
                    "ENDVERTEX_XERR": None,
                    "ENDVERTEX_YERR": None,
                    "ENDVERTEX_ZERR": None,
                    "ENDVERTEX_CHI2": None,
                    "ENDVERTEX_NDOF": None,
                    "ENDVERTEX_COV_": None,
                    "M": None,
                    "MMERR": None,
                    "ID": None,
                },
                "J_psi_1S": {
                    "ENDVERTEX_X": None,
                    "ENDVERTEX_Y": None,
                    "ENDVERTEX_Z": None,
                    "ENDVERTEX_XERR": None,
                    "ENDVERTEX_YERR": None,
                    "ENDVERTEX_ZERR": None,
                    "ENDVERTEX_CHI2": None,
                    "ENDVERTEX_NDOF": None,
                    "ENDVERTEX_COV_": None,
                    "M": None,
                    "MMERR": None,
                    "ID": None,
                },
            }

        },

    }


    metadata = {
        "nCandidate": None,
        "totCandidates": None,
        "EventInSequence": None,
        "runNumber": None,
        "eventNumber": None,
        "BCID": None,
        "BCType": None,
        "OdinTCK": None,
        "L0DUTCK": None,
        "HLT1TCK": None,
        "HLT2TCK": None,
        "GpsTime": None,
        "Polarity": None,
        "IntegratedLuminosity": None,
        "IntegratedLuminosityErr": None,
    }


def create_godot():
    pass

def main():
    pass

if __name__ == '__main__':
    main()
